name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Katmandu
          config_display: large
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 20
          plugin_habits_facts: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_limit: 8
          plugin_repositories: yes
          plugin_repositories_featured: carch-org/carch, carch-org/pkgs, carch-org/docs
          plugin_repositories_affiliations: owner, collaborator

