name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Katmandu
          config_display: large
          plugin_activity: yes
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 20
          plugin_habits_facts: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors-graphs, os-graphs
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_limit: 8
          plugin_repositories: yes
          plugin_repositories_featured: carch-org/pkgs, carch-org/docs, carch-org/wiki
          plugin_repositories_affiliations: owner, collaborator
          plugin_licenses: yes

